### ISSUE TITLE
Portal

### ISSUE THREAD

**Issue by Maryasych** [enable3d/enable3d#21]
Is it possible to make portal in mesh?
I have a wall with a doorway. If add physic to the wall as "hacd", collide event fired few times on a wall, if add as "plane", event fire once, but plane cover all wall include a doorway.
Or how to fire collide event on “hacd” mesh once?

**Comment by yandeu** [comment]
Can you upload a screenshot that I can better imagine the situation?

> I have a wall with a doorway.

Have you tried to use a custom compound shape of multiple boxes? One large on top, two smaller on the side.

> Or how to fire collide event on “hacd” mesh once?

You have to wrap your custom function around `body.on.collision`

Btw: 
-  _I always suggest using boxes instead of planes._
-  _I always suggest compound shapes instead of  hacd (if possible)._

**Comment by Maryasych** [comment]
https://maryasych.github.io/enable3DPhysic/
events prints to console.

Plane shape: hacd

THREE.Mesh: on spheres trigger collision event same time. Think ExtendedMesh should marked large, bold font size.

> Have you tried to use a custom compound shape of multiple boxes? One large on top, two smaller on the side.

I don't see a way to change 'shape' on objects like this.

**Comment by yandeu** [comment]
I see the issue. It really is a problem with the hacd shape. I have tested it with the code below. I will investigate it and provide a fix.

```js
this.warpSpeed('-ground')

let ground = this.add.box({ width: 20, depth: 20 })
this.physics.add.existing(ground, { shape: 'hacd', mass: 0, collisionFlags: 1 })

const box = this.physics.add.box({ y: 10 })

box.body.on.collision((otherObject, event) => {
  if (event === 'start') console.log(`box and ${otherObject.name}: ${event}`)
})
```
