### ISSUE TITLE
Terrain RGBA splatmapping / steep slope physics?

### ISSUE THREAD

**Issue by Thundros** [enable3d/enable3d#22]
Hi @yandeu ! So i would like to beta test an RGBA splatmapped terrain. http://wiki.polycount.com/wiki/Splat this is an RGBA splatmap. and terrain slope physics is where the character slowly slides down to a stop when trying to climb very steep parts of the terrain.

Once again, please give yourself a huge pat on the back for doing this amazing work!

**Comment by yandeu** [comment]
I added support for Slope Angles using the Physics Raycaster. Here [is an example](https://enable3d.io/examples/slope-angle-and-moving-platform.html). (It will only work in the next release of enable3d, but you can already take a look at the source code)

---

Splat Maps are not included in three.js. You have to write custom shaders to implement it. Here is an [example](http://stemkoski.github.io/Three.js/Shader-Heightmap-Textures.html). Since you have access to every three.js function in enable3d, I guess you could implement it on your own studying the example. I'm not sure if I will implement a wrapper function for it. Maybe I will try it and publish an example on the enable3d website.

For now, I guess we can close this issue.
