### ISSUE TITLE
Use with Phaser 3D as 2.5D Engine?

### ISSUE THREAD

**Issue by jdiperla** [enable3d/enable3d#78]
Is there a tutorial where we can place a 3d object on top of a 2d Phaser world and have it interact with that? I am not seeing much in the way of how this is supposed to work with phaser when all we are editing is a config file. Maybe I am missing something...

**Comment by HadrienRivere** [comment]
I don't think it is possible since Enable 3D is 3d. Well there are some examples like these.

https://enable3d.io/examples/sync-2d-to-3d.html
https://enable3d.io/examples/sync-3d-to-2d.html
https://enable3d.io/examples/switch-camera-between-2d-and-3d.html

Well that's not everything, maybe @yannick can help you.

**Comment by yandeu** [comment]
Thx @HadrienRivere, these examples should help.

Theoretically, it should be possible. It should even be possible to attach phaser's arcade physics to a 3d element.

But unfortunately the 3d elements will always be rendered below the 2d elements. But I guess you could also render sprites inside the 3d canvas, which then would solve the issue.

I will make an example.

**Comment by yandeu** [comment]
I guess this issue can be closed since it is now possible to render 2d objects on the 3d canvas.
