### ISSUE TITLE
 memory access out of bound

### ISSUE THREAD

**Issue by HadrienRivere** [enable3d/enable3d#97]
Sometimes I run into these kinds of errors. These do not seem to affect the game but are constant. Do you know why?

Error

![Image of error](https://i.imgur.com/lfJRA76.png)

Line: 134

![Image of error](https://i.imgur.com/0rDPJTa.png)

**Comment by yandeu** [comment]
No, I don't know why. It clearly looks like an ammo.js issue.

Maybe you are shooting too many balls and they all get stuck in memory? Maybe you should destroy balls that are not needed anymore or recycle them. Recycling is probably the most efficient.

Btw `bufferGeometry: true` is the default. It will be removed in the next version. Since three.js r125, non-bufferGeometry are not supported anymore. This means all Geometries needs to be BufferGeometries.

**Comment by HadrienRivere** [comment]
Well I have followed your advice.

```javascript


create() {
    this.map.body.on.collision((otherObject, event) => {
      if (otherObject.uuid === '101') {
        this.bulletesGroup.map((e) => {
          const currenbulletesGroup = this.bulletesGroup.filter(item => item.uuid !== e.uuid);
          this.bulletesGroup = currenbulletesGroup;
          this.destroy(e)
        })
      }
    })
}

update() {
      if (this.bulletesGroup) {
        this.bulletesGroup.map((e) => {
          if (e.position.y <= 0) {
            const currenbulletesGroup = this.bulletesGroup.filter(item => item.uuid !== e.uuid);
            this.bulletesGroup = currenbulletesGroup;
            this.destroy(e)
          }
        })
      }

}


```


I have uploaded a demo here:  https://uncached.gamemonetize.com/9qlk2shk875goqwss2jk0c6t0lgj8lmi/

Sorry about the ads is the only way I can upload files in production.

**Comment by yandeu** [comment]
Check out this new example about recyling:
https://enable3d.io/examples/objects-recycling.html

**Comment by HadrienRivere** [comment]
> Check out this new example about recyling:
> https://enable3d.io/examples/objects-recycling.html

😱😱😱😱😱😱 COOL
